using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace AssetRipper.Tools.UnityPackageGuidCollector;

internal static class Program
{
	private const string AutoGeneratedHeader = "// <auto-generated>由 AssetRipper.Tools.UnityPackageGuidCollector 生成。请勿手动编辑。</auto-generated>";

	// Unity 所有 .meta 文件均以 "guid:" 行标记资源 GUID
	private const string GuidPrefix = "guid:";

	// 采集逻辑用到的 JSON 宽松选项：Unity 部分 .asmdef / package.json 含注释或尾随逗号
	private static readonly JsonDocumentOptions s_jsonOptions = new()
	{
		AllowTrailingCommas = true,
		CommentHandling = JsonCommentHandling.Skip,
	};

	// 仅在字符串含特殊字符时才走 StringBuilder 转义，避免无谓分配
	private static readonly char[] s_charsNeedingEscape = ['\\', '"'];

	// 提取命名空间声明，兼容块作用域和文件作用域两种写法
	// 例如 "namespace UnityEngine.UI {" 和 "namespace Foo.Bar;" 均可匹配
	private static readonly Regex s_namespaceRegex = new(@"namespace\s+([\w.]+)", RegexOptions.Compiled);

	// 提取类型声明（class/struct/interface/enum/record），关键词为 C# 保留字不会误匹配标识符
	// 仅可能匹配到注释中的内容，但 false positive 只会添加无用条目，不影响正确性
	private static readonly Regex s_typeRegex = new(@"\b(?:class|struct|interface|enum|record)\s+(\w+)", RegexOptions.Compiled);

	private static int Main(string[] args)
	{
		if (args.Length != 3)
		{
			Console.Error.WriteLine("用法: UnityPackageGuidCollector <BuiltInPackages路径> <PackageCache路径> <输出文件路径>");
			return 1;
		}

		string builtInPackagesPath = args[0];
		string packageCachePath = args[1];
		string outputPath = args[2];

		Dictionary<string, Entry> entries = new(StringComparer.Ordinal);
		// 记录每个程序集的 .asmdef 文件路径，供脚本扫描使用
		Dictionary<string, string> asmdefPaths = new(StringComparer.Ordinal);

		CollectFromDirectory(builtInPackagesPath, EntrySource.BuiltInPackages, entries, asmdefPaths);
		CollectFromDirectory($@"{packageCachePath}\Library\PackageCache", EntrySource.PackageCache, entries, asmdefPaths);
		CollectFromDirectory($@"{packageCachePath}\Assets\Plugins", EntrySource.PackageCache, entries, asmdefPaths);

		// 扫描 .cs + .cs.meta，建立脚本级 GUID 映射
		List<ScriptEntry> scriptEntries = new();
		foreach (KeyValuePair<string, string> kvp in asmdefPaths)
		{
			ScanScriptFiles(kvp.Value, kvp.Key, scriptEntries);
		}

		WriteOutputFile(outputPath, entries, scriptEntries);
		Console.WriteLine($"已采集 {entries.Count} 条程序集记录、{scriptEntries.Count} 条脚本记录，输出到: {outputPath}");
		return 0;
	}

	private static void CollectFromDirectory(string rootPath, EntrySource source, Dictionary<string, Entry> entries, Dictionary<string, string> asmdefPaths)
	{
		if (!Directory.Exists(rootPath))
		{
			Console.Error.WriteLine($"警告: 目录不存在，跳过采集: {rootPath}");
			return;
		}

		string rootFull = Path.GetFullPath(rootPath);
		foreach (string asmdefPath in Directory.EnumerateFiles(rootFull, "*.asmdef", SearchOption.AllDirectories))
		{
			try
			{
				ProcessAsmdef(asmdefPath, rootFull, source, entries, asmdefPaths);
			}
			catch (Exception ex)
			{
				// 单个文件失败不应中断整体采集流程，仅记录后继续
				Console.Error.WriteLine($"警告: 处理失败，跳过: {asmdefPath}。原因: {ex.Message}");
			}
		}
	}

	private static void ProcessAsmdef(string asmdefPath, string searchRoot, EntrySource source, Dictionary<string, Entry> entries, Dictionary<string, string> asmdefPaths)
	{
		string metaPath = asmdefPath + ".meta";
		if (!File.Exists(metaPath))
		{
			Console.Error.WriteLine($"警告: 缺少 .asmdef.meta，跳过: {asmdefPath}");
			return;
		}

		string? guid = ReadGuidFromMeta(metaPath);
		if (guid is null)
		{
			Console.Error.WriteLine($"警告: 无法从 .meta 读取合法 guid，跳过: {metaPath}");
			return;
		}

		string? assemblyName = ReadAssemblyNameFromAsmdef(asmdefPath);
		if (string.IsNullOrEmpty(assemblyName))
		{
			Console.Error.WriteLine($"警告: 无法从 .asmdef 读取 name 字段，跳过: {asmdefPath}");
			return;
		}

		(string? packageName, string? version) = ReadPackageInfo(asmdefPath, searchRoot);
		if (string.IsNullOrEmpty(packageName) || string.IsNullOrEmpty(version))
		{
			Console.Error.WriteLine($"警告: 缺少 package.json 或 name/version 字段，跳过: {asmdefPath}");
			return;
		}

		Entry entry = new(assemblyName, packageName, guid, version, source);
		// TryGetValue 返回 true 时 existing 必非空，故在 if 体内可直接访问而无需空判断
		if (entries.TryGetValue(assemblyName, out Entry? existing))
		{
			if (source == EntrySource.PackageCache && existing.Source == EntrySource.BuiltInPackages)
			{
				// PackageCache 优先：覆盖 BuiltInPackages 的同名记录，asmdefPaths 同步覆盖
				Console.Error.WriteLine($"警告: 程序集 '{assemblyName}' 同时存在于 BuiltInPackages 与 PackageCache，采用 PackageCache 版本。");
				entries[assemblyName] = entry;
				asmdefPaths[assemblyName] = asmdefPath;
			}
			else
			{
				// 同源重复，或 BuiltInPackages 与已记录的 PackageCache 冲突：保留先记录的版本
				Console.Error.WriteLine($"警告: 程序集 '{assemblyName}' 重复出现，保留已记录的版本，忽略来自 {source} 的记录。");
			}
		}
		else
		{
			entries[assemblyName] = entry;
			asmdefPaths[assemblyName] = asmdefPath;
		}
	}

	private static string? ReadGuidFromMeta(string metaPath)
	{
		foreach (string line in File.ReadLines(metaPath))
		{
			if (line.StartsWith(GuidPrefix, StringComparison.Ordinal))
			{
				string guid = line.Substring(GuidPrefix.Length).Trim();
				// 统一输出小写，与 .meta 原始形式保持一致
				return IsValidHexGuid(guid) ? guid.ToLowerInvariant() : null;
			}
		}
		return null;
	}

	private static bool IsValidHexGuid(string value)
	{
		if (value.Length != 32)
		{
			return false;
		}
		foreach (char c in value)
		{
			if (!IsHexDigit(c))
			{
				return false;
			}
		}
		return true;
	}

	private static bool IsHexDigit(char c)
		=> (uint)(c - '0') <= 9u
			|| (uint)(c - 'a') <= 5u
			|| (uint)(c - 'A') <= 5u;

	private static string? ReadAssemblyNameFromAsmdef(string asmdefPath)
	{
		using FileStream stream = File.OpenRead(asmdefPath);
		using JsonDocument doc = JsonDocument.Parse(stream, s_jsonOptions);
		return doc.RootElement.TryGetProperty("name", out JsonElement nameEl) ? nameEl.GetString() : null;
	}

	private static (string? Name, string? Version) ReadPackageInfo(string asmdefPath, string searchRoot)
	{
		// 从 .asmdef 所在目录向上查找最近的 package.json，并限定在搜索根范围内
		string searchRootFull = Path.GetFullPath(searchRoot);
		DirectoryInfo? dir = new DirectoryInfo(Path.GetDirectoryName(asmdefPath)!);
		while (dir is not null)
		{
			string packageJsonPath = Path.Combine(dir.FullName, "package.json");
			if (File.Exists(packageJsonPath))
			{
				return ParsePackageJson(packageJsonPath);
			}

			// 抵达搜索根即停止上溯，避免读到采集范围之外的 package.json
			string dirFull = Path.GetFullPath(dir.FullName);
			if (string.Equals(dirFull, searchRootFull, StringComparison.OrdinalIgnoreCase))
			{
				break;
			}
			dir = dir.Parent;
		}
		return (null, null);
	}

	private static (string? Name, string? Version) ParsePackageJson(string path)
	{
		using FileStream stream = File.OpenRead(path);
		using JsonDocument doc = JsonDocument.Parse(stream, s_jsonOptions);
		JsonElement root = doc.RootElement;
		string? name = root.TryGetProperty("name", out JsonElement nameEl) ? nameEl.GetString() : null;
		string? version = root.TryGetProperty("version", out JsonElement versionEl) ? versionEl.GetString() : null;
		return (name, version);
	}

	private static void WriteOutputFile(string outputPath, Dictionary<string, Entry> entries, List<ScriptEntry> scriptEntries)
	{
		// 按程序集名排序，保证生成内容稳定，便于代码审查与 diff
		List<Entry> sorted = entries.Values.OrderBy(e => e.AssemblyName, StringComparer.Ordinal).ToList();

		// 脚本条目按 (AssemblyName, Namespace, ClassName) 排序，保证输出稳定
		// 同一复合键出现多次时只保留第一个，避免字典出现重复键
		List<ScriptEntry> sortedScripts = scriptEntries
			.OrderBy(s => s.AssemblyName, StringComparer.Ordinal)
			.ThenBy(s => s.Namespace, StringComparer.Ordinal)
			.ThenBy(s => s.ClassName, StringComparer.Ordinal)
			.ToList();

		// 用字符串常量存储数据，静态构造函数中逐行解析填充字典。
		// 避免超大集合初始化器导致 JIT 生成的 .cctor 方法体过大而栈溢出。
		// 格式：A|AssemblyName|PackageName|Guid|Version  或  S|AssemblyName|Namespace|ClassName|Guid
		StringBuilder data = new();
		foreach (Entry e in sorted)
		{
			data.Append("A|").Append(e.AssemblyName).Append('|')
				.Append(e.PackageName).Append('|')
				.Append(e.Guid).Append('|')
				.Append(e.Version).Append('\n');
		}
		HashSet<(string Assembly, string Namespace, string Class)> seenScriptKeys = new();
		foreach (ScriptEntry s in sortedScripts)
		{
			if (!seenScriptKeys.Add((s.AssemblyName, s.Namespace, s.ClassName)))
			{
				Console.Error.WriteLine($"警告: 脚本类型 ('{s.AssemblyName}', '{s.Namespace}', '{s.ClassName}') 重复出现，保留首个 GUID，忽略后续。");
				continue;
			}
			data.Append("S|").Append(s.AssemblyName).Append('|')
				.Append(s.Namespace).Append('|')
				.Append(s.ClassName).Append('|')
				.Append(s.Guid).Append('\n');
		}

		StringBuilder sb = new();
		sb.AppendLine(AutoGeneratedHeader);
		sb.AppendLine("using AssetRipper.Primitives;");
		sb.AppendLine("using System.Collections.Generic;");
		sb.AppendLine("using System.IO;");
		sb.AppendLine();
		sb.AppendLine("namespace AssetRipper.Export.UnityProjects.Scripts;");
		sb.AppendLine();
		sb.AppendLine("public static class UnityPackageAssemblyMap");
		sb.AppendLine("{");
		// 数据用 verbatim 字符串存储。字段假设不含 " 和 \n 和 |（程序集名/命名空间/类名/GUID 均满足）
		sb.AppendLine("\tprivate const string Data = @\"");
		// verbatim 字符串中的 " 需要写成 ""，但数据字段不含 "
		sb.Append(data.ToString().Replace("\"", "\"\""));
		sb.AppendLine("\";");
		sb.AppendLine();
		sb.AppendLine("\tprivate static readonly Dictionary<string, UnityPackageAssemblyInfo> s_map = new();");
		sb.AppendLine("\tprivate static readonly Dictionary<(string assemblyName, string @namespace, string className), UnityGuid> s_scriptGuidMap = new();");
		sb.AppendLine();
		sb.AppendLine("\tstatic UnityPackageAssemblyMap()");
		sb.AppendLine("\t{");
		sb.AppendLine("\t\tusing StringReader reader = new(Data);");
		sb.AppendLine("\t\tstring? line;");
		sb.AppendLine("\t\twhile ((line = reader.ReadLine()) is not null)");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\tif (line.Length == 0)");
		sb.AppendLine("\t\t\t{");
		sb.AppendLine("\t\t\t\tcontinue;");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t\tstring[] parts = line.Split('|');");
		sb.AppendLine("\t\t\tif (parts[0] == \"A\" && parts.Length == 5)");
		sb.AppendLine("\t\t\t{");
		sb.AppendLine("\t\t\t\ts_map[parts[1]] = new UnityPackageAssemblyInfo(parts[2], UnityGuid.Parse(parts[3]), parts[4]);");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t\telse if (parts[0] == \"S\" && parts.Length == 5)");
		sb.AppendLine("\t\t\t{");
		sb.AppendLine("\t\t\t\ts_scriptGuidMap[(parts[1], parts[2], parts[3])] = UnityGuid.Parse(parts[4]);");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
		sb.AppendLine();
		sb.AppendLine("\tpublic static bool TryGetInfo(string assemblyName, out UnityPackageAssemblyInfo info)");
		sb.AppendLine("\t\t=> s_map.TryGetValue(assemblyName, out info);");
		sb.AppendLine();
		sb.AppendLine("\tpublic static bool TryGetScriptGuid(string assemblyName, string @namespace, string className, out UnityGuid guid)");
		sb.AppendLine("\t\t=> s_scriptGuidMap.TryGetValue((assemblyName, @namespace, className), out guid);");
		sb.AppendLine("}");

		string? dir = Path.GetDirectoryName(outputPath);
		if (!string.IsNullOrEmpty(dir))
		{
			Directory.CreateDirectory(dir);
		}
		File.WriteAllText(outputPath, sb.ToString());
	}

	private static string FormatGuidAsUInts(string guid)
	{
		// 把 32 位十六进制 GUID 按字符串顺序拆成 4 段 uint 十六进制字面量。
		// 例如 "df380645f10b7bc4b97d4f5eb6303d95" => "0xdf380645u, 0xf10b7bc4u, 0xb97d4f5eu, 0xb6303d95u"
		// 用Substring而非Span切片以保持代码可读性；GUID 长度恒为 32，无边界风险。
		return $"0x{guid.Substring(0, 8)}u, 0x{guid.Substring(8, 8)}u, 0x{guid.Substring(16, 8)}u, 0x{guid.Substring(24, 8)}u";
	}

	private static string Escape(string value)
	{
		// 转义 C# 字符串字面量中的反斜杠与双引号
		if (value.IndexOfAny(s_charsNeedingEscape) < 0)
		{
			return value;
		}
		StringBuilder sb = new(value.Length + 2);
		foreach (char c in value)
		{
			switch (c)
			{
				case '\\':
					sb.Append("\\\\");
					break;
				case '"':
					sb.Append("\\\"");
					break;
				default:
					sb.Append(c);
					break;
			}
		}
		return sb.ToString();
	}

	private static void ScanScriptFiles(string asmdefPath, string assemblyName, List<ScriptEntry> scriptEntries)
	{
		// .asmdef 所在目录即为该程序集的源码根目录
		string asmdefDir = Path.GetDirectoryName(asmdefPath)!;
		if (!Directory.Exists(asmdefDir))
		{
			return;
		}

		// 收集该目录下所有子目录中的 .asmdef，用于判断 .cs 文件是否属于当前程序集
		// 若 .cs 文件所在目录的最近祖先 .asmdef 不是当前这个，则跳过（属于另一个程序集）
		HashSet<string> otherAsmdefDirs = new(StringComparer.OrdinalIgnoreCase);
		foreach (string otherAsmdef in Directory.EnumerateFiles(asmdefDir, "*.asmdef", SearchOption.AllDirectories))
		{
			if (!string.Equals(otherAsmdef, asmdefPath, StringComparison.OrdinalIgnoreCase))
			{
				otherAsmdefDirs.Add(Path.GetDirectoryName(otherAsmdef)!);
			}
		}

		foreach (string csPath in Directory.EnumerateFiles(asmdefDir, "*.cs", SearchOption.AllDirectories))
		{
			// 跳过属于其他 .asmdef 的 .cs 文件
			string? csDir = Path.GetDirectoryName(csPath);
			if (csDir is not null && IsUnderAnyDir(csDir, otherAsmdefDirs))
			{
				continue;
			}

			string csMetaPath = csPath + ".meta";
			if (!File.Exists(csMetaPath))
			{
				continue;
			}

			string? guid = ReadGuidFromMeta(csMetaPath);
			if (guid is null)
			{
				continue;
			}

			// 解析 .cs 文件提取命名空间和类型声明
			string content;
			try
			{
				content = File.ReadAllText(csPath);
			}
			catch (Exception ex)
			{
				Console.Error.WriteLine($"警告: 读取 .cs 文件失败，跳过: {csPath}。原因: {ex.Message}");
				continue;
			}

			string ns = ExtractNamespace(content);
			List<string> typeNames = ExtractTypeNames(content);
			foreach (string typeName in typeNames)
			{
				scriptEntries.Add(new ScriptEntry(assemblyName, ns, typeName, guid));
			}
		}
	}

	/// <summary>
	/// 判断 path 是否等于或位于 dirs 中任一目录之下。
	/// 用于判断 .cs 文件是否属于更近的 .asmdef。
	/// </summary>
	private static bool IsUnderAnyDir(string path, HashSet<string> dirs)
	{
		string pathFull = Path.GetFullPath(path);
		foreach (string dir in dirs)
		{
			string dirFull = Path.GetFullPath(dir);
			if (pathFull.StartsWith(dirFull, StringComparison.OrdinalIgnoreCase))
			{
				return true;
			}
		}
		return false;
	}

	private static string ExtractNamespace(string content)
	{
		Match m = s_namespaceRegex.Match(content);
		return m.Success ? m.Groups[1].Value : "";
	}

	private static List<string> ExtractTypeNames(string content)
	{
		List<string> names = new();
		foreach (Match m in s_typeRegex.Matches(content))
		{
			names.Add(m.Groups[1].Value);
		}
		return names;
	}

	private sealed record Entry(string AssemblyName, string PackageName, string Guid, string Version, EntrySource Source);

	// 单个脚本（.cs 文件）的 GUID 映射条目
	// 一个 .cs 文件可能声明多个类型，每个类型共享同一个 .cs.meta GUID
	private sealed record ScriptEntry(string AssemblyName, string Namespace, string ClassName, string Guid);

	private enum EntrySource
	{
		BuiltInPackages,
		PackageCache,
	}
}
